### ISSUE TITLE
Provide working maven example

### ISSUE THREAD

**Issue by GuyJackson** [awslabs/aws-lambda-powertools-java#726]
I'm trying to trial Powertools in my demo project (specifically around logging).

I've copied [this pom](https://github.com/awslabs/aws-lambda-powertools-java/blob/master/example/HelloWorldFunction/pom.xml) in your example repo and get a series of issues in my demo project - when I package (`mvn clean package`) and upload the produced jar to aws. 

**1.**  Cloudwatch error - Exception when using `private final static Logger log = LogManager.getLogger();` in [App](https://github.com/awslabs/aws-lambda-powertools-java/blob/master/example/HelloWorldFunction/src/main/java/helloworld/App.java#L37) class.

> java.lang.ExceptionInInitializerError
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Unknown Source)
> Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.

Resolved by putting in `private final static Logger log = LogManager.getLogger(**App.class**);`

**2.** Cloudwatch error - Exception related to maven shade plugin:

> ERROR StatusLogger Unrecognized conversion specifier [d]

Seems to relate to [this](https://stackoverflow.com/questions/48033792/log4j2-error-statuslogger-unrecognized-conversion-specifier) stackoverflow post.

Resolved by adding this config to the shade plugin:

```
<configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <finalName>hello-world</finalName>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>**/Log4j2Plugins.dat</exclude>
                                <exclude>module-info.class</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
```

**3.** Cloudwatch warning:

> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

Not entirely sure on the resolution for this but doesn't break things as it stands.

**4.** Cloudwatch Error related to log4j2.xml which is copied from your repo [here.](https://github.com/awslabs/aws-lambda-powertools-java/blob/master/example/HelloWorldFunction/src/main/resources/log4j2.xml)

> ERROR Console contains an invalid element or attribute "LambdaJsonLayout"

I don't know how to progress past this.

Many Thanks,

**Comment by orozcoadrian** [comment]
I've seen some of these errors as well. Looks like that `example` folder in the repo has not been kept up-to-date with recent documentation changes. In the meantime you could try following the docs instead of that sample code: https://awslabs.github.io/aws-lambda-powertools-java/

In the end was able to get both a maven and a gradle lambda working by following the docs.

**Comment by GuyJackson** [comment]
Thanks @orozcoadrian that was my original first point of call. Adding the following the [install steps](https://awslabs.github.io/aws-lambda-powertools-java/#install) then adding the example[ log4j2.xml](https://awslabs.github.io/aws-lambda-powertools-java/core/logging/#initialization) into resources, resulted in me getting this error in the Cloudwatch logs:

> ERROR Console contains an invalid element or attribute "JsonTemplateLayout"

Since getting the above error, I had a sniff around for examples and came here...

It's not entirely clear to me from the docs what other additional dependencies need to be included for this to work re: log4j2.

**Comment by pankajagrawal16** [comment]
> Thanks @orozcoadrian that was my original first point of call. Following the [install steps](https://awslabs.github.io/aws-lambda-powertools-java/#install) then adding the example[ log4j2.xml](https://awslabs.github.io/aws-lambda-powertools-java/core/logging/#initialization) into resources, resulted in me getting this error in the Cloudwatch logs:
> 
> > ERROR Console contains an invalid element or attribute "JsonTemplateLayout"
> 
> Since getting the above error, I had a sniff around for examples and came here...
> 
> It's not entirely clear to me from the docs what other additional dependencies need to be included for this to work re: log4j2.

Hi @GuyJackson Which version of powertools are you using ?

**Comment by pankajagrawal16** [comment]
I would also recommend using quick start template documented here https://awslabs.github.io/aws-lambda-powertools-java/ to get a sample maven or gradle app. 

Note, Support for `JsonTemplateLayout ` was introduced in version [v1.10.0](https://awslabs.github.io/aws-lambda-powertools-java/changelog/#1100-2021-12-27)

**Comment by pankajagrawal16** [comment]
Also as @orozcoadrian pointed, please avoid referring `example` folder within the project. We will soon be moving it out of the project itself.

**Comment by GuyJackson** [comment]
@pankajagrawal16 thanks for the reply, I'm using `1.10.2` version of powertools. I missed the cookie cutter in the docs:

`sam init --location gh:aws-samples/cookiecutter-aws-sam-powertools-java`

Will see what that produces.

**Comment by pankajagrawal16** [comment]
> 

Cool, Let us know how it goes. :)

**Comment by GuyJackson** [comment]
running:

`sam init --location gh:aws-samples/cookiecutter-aws-sam-powertools-java`

I get errors on windows and linux (on different machines).

Windows errors:

**Comment by pankajagrawal16** [comment]
Hmm , this seems odd. I cannot seem to replicate this issue on mac atleast. Do you have any more logs to share?

**Comment by GuyJackson** [comment]
@pankajagrawal16 My colleague who has a Mac also confirmed it to be working (like you) and shared the generated project with me. I have a suspicion it's perhaps just a windows / linux issue but will share logs when I have looked at it a bit further.

Using the generated project shared by my colleague, one thing I did notice was the same issue with this line in `App`:

`Logger log = LogManager.getLogger();`

If you leave as is you get this CW error:

> No class provided, and an appropriate one cannot be found.: java.lang.UnsupportedOperationException
> java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.

`Logger log = LogManager.getLogger(App.class);` resolves the issue.

**Comment by pankajagrawal16** [comment]
Ok great that you got it working. Regarding error on initializing logger, its totally fine to provide class explicitly if log4j is not able to figure it out itself.

I suspect this issue https://stackoverflow.com/questions/52953483/logmanager-getlogger-is-unable-to-determine-class-name-on-java-11 might be related with your project.

Feel free to close the issue if all is good.
