### ISSUE TITLE
RFC:  bump aws-embedded-metrics from 1.0.6 to 4.0.1

### ISSUE THREAD

**Issue by kozub** [awslabs/aws-lambda-powertools-java#944]
## Key information

* RFC PR: (leave this empty)
* Related issue(s), if known: https://github.com/awslabs/aws-lambda-powertools-java/pull/943
* Area: (i.e. Tracer, Metrics, Logger, etc.) Metric
* Meet [tenets](https://awslabs.github.io/aws-lambda-powertools-java/#tenets): (Yes/no)

## Summary
[summary]: #summary

> There are some work required to bump aws-embedded-metrics to 4.0.1

## Motivation
[motivation]: #motivation

I had a quick look on the issue that appeared when dependabot bumped aws-embedded-metrics to 4.0.1. 

I looks that in latest version some components of aws-embedded-metrics throw checked exceptions which are not handled in the app. I will create a PR showing the issue and fix.

**Comment by n8m8** [comment]
Work on this would be much appreciated, I'm running into these excessive socket error logs upon using `MetricsUtils.withSingleMetric` when running unit tests, which I've been suggested can be reduced by bumping `aws-embedded-metrics` to > 2.x.

```
ERROR TCPClient:43 - Failed to connect to the socket due to the exception: 
java.net.SocketException: Socket closed
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_332]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_332]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_332]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_332]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_332]
    at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_332]
    at java.net.Socket.connect(Socket.java:556) ~[?:1.8.0_332]
    at software.amazon.cloudwatchlogs.emf.sinks.TCPClient.connect(TCPClient.java:40) ~[aws-embedded-metrics-1.0.6.jar:1.0.6]
    at software.amazon.cloudwatchlogs.emf.sinks.TCPClient.sendMessage(TCPClient.java:63) ~[aws-embedded-metrics-1.0.6.jar:1.0.6]
    at software.amazon.cloudwatchlogs.emf.sinks.AgentSink.accept(AgentSink.java:52) ~[aws-embedded-metrics-1.0.6.jar:1.0.6]
    at software.amazon.cloudwatchlogs.emf.logger.MetricsLogger.flush(MetricsLogger.java:66) ~[aws-embedded-metrics-1.0.6.jar:1.0.6]
    at software.amazon.lambda.powertools.metrics.MetricsUtils.withSingleMetric(MetricsUtils.java:120) ~[powertools-metrics-1.12.2.jar:?]
```

**Comment by markkuhn** [comment]
I would recommend using v4.0.3 instead as there is a [known bug](https://github.com/awslabs/aws-embedded-metrics-java/issues/127) in v4.0.1 which affects most users.

**Comment by jeromevdl** [comment]
This introduces breaking changes: 
A simple `metricsLogger.putMetric(...)` now throws checked exception (`InvalidMetricException`).

This should be released in a v2 of lambda-powertools-metrics.

**Comment by msailes** [comment]
I'm going to close this issue because we have a much clearer issue and reason why we want to upgrade now. #1041 requires v4.x and gives an additional feature we want to support.
